name: 30 License Compliance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-finder:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup Java & Maven"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: "Ensure Maven Dependencies are Installed"
        run: mvn dependency:resolve || mvn dependency:resolve -DskipTests

      - name: "Run License Finder"
        uses: jmservera/license-finder-action@main
        continue-on-error: true # Avoid workflow failure on minor issues
        with:
          permitted-licenses: MIT,Apache-2.0,BSD,EPL1
          approved-dependencies: |
            hamcrest,hamcrest-core,hamcrest-library
            junit-jupiter,junit-jupiter-api,junit-jupiter-engine,javax.annotation-api

      - name: "Upload License Finder Report"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-finder-report
          path: ${{ github.workspace }}/license_finder_report.xml
